# Generated by Django 5.2.17 on 2026-10-05 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coin_amount', models.PositiveIntegerField()),
                ('price_krw', models.PositiveIntegerField()),
                ('paddle_price_id', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coin_products',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_amount', models.PositiveIntegerField()),
                ('price_krw', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', '결제 대기'), ('PAID', '결제 완료'), ('EXPIRED', '만료'), ('REFUNDED', '환불')], default='PENDING', max_length=10)),
                ('paddle_transaction_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.coinproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_orders',
            },
        ),
        migrations.CreateModel(
            name='PaddleWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('PROCESSED', '처리 완료'), ('IGNORED', '무시'), ('DATA_ERROR', '데이터 오류')], default='PROCESSED', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paymentorder')),
            ],
            options={
                'db_table': 'paddle_webhook_events',
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddle_adjustment_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '거절')], default='PENDING', max_length=10)),
                ('refund_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('coins_revoked', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentorder')),
            ],
            options={
                'db_table': 'payment_refunds',
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'created_at'], name='ix_order_user'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'created_at'], name='ix_order_status'),
        ),
    ]
