# Generated by Django 5.2.17 on 2026-10-05 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_ratio', models.PositiveSmallIntegerField()),
                ('one_line', models.CharField(blank=True, max_length=255, null=True)),
                ('case_summary', models.TextField(blank=True, null=True)),
                ('judgment_text', models.TextField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='cases.case')),
            ],
            options={
                'db_table': 'verdicts',
            },
        ),
        migrations.CreateModel(
            name='VerdictReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='verdicts.verdict')),
            ],
            options={
                'db_table': 'verdict_reasons',
            },
        ),
        migrations.CreateModel(
            name='VerdictReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('KIND', '다정한'), ('FIRM', '단호한'), ('COOL', '담백한')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='verdicts.verdict')),
            ],
            options={
                'db_table': 'verdict_replies',
            },
        ),
        migrations.CreateModel(
            name='VerdictRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '처리대기'), ('RUNNING', '처리중'), ('DONE', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('progress_step', models.CharField(blank=True, max_length=30, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdict_requests', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verdict_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verdict_requests',
            },
        ),
        migrations.AddField(
            model_name='verdict',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='verdicts.verdictrequest'),
        ),
    ]
