# Generated by Django 5.2.17 on 2026-10-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdicts', '0003_request_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdictreply',
            name='tone',
        ),
    ]
