# Generated by Django 5.2.17 on 2026-10-09 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdicts', '0004_remove_verdictreply_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='input_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='verdict',
            name='public_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verdict',
            name='public_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='verdict',
            name='relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verdict',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='VerdictFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('side', models.CharField(choices=[('SELF', '본인'), ('OTHER', '상대')], max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='verdicts.verdict')),
            ],
            options={
                'db_table': 'verdict_factors',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VerdictFactorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SCHOLAR', '논문'), ('WEB', '기사')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2048)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('published_date', models.CharField(blank=True, max_length=50)),
                ('reference_summary', models.TextField()),
                ('factor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='verdicts.verdictfactor')),
            ],
            options={
                'db_table': 'verdict_factor_sources',
            },
        ),
        migrations.CreateModel(
            name='VerdictShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='verdicts.verdict')),
            ],
            options={
                'db_table': 'verdict_shares',
            },
        ),
        migrations.AddConstraint(
            model_name='verdictfactor',
            constraint=models.UniqueConstraint(fields=('verdict', 'key'), name='unique_verdict_factor_key'),
        ),
    ]
