# Generated by Django 5.2.17 on 2026-10-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdicts', '0005_verdict_input_snapshot_verdict_public_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdictrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '처리대기'), ('RUNNING', '처리중'), ('DONE', '완료'), ('FAILED', '실패'), ('AWAITING_CONFIRMATION', '상황 확인 대기'), ('CANCELED', '취소')], default='PENDING', max_length=30),
        ),
    ]
