# Generated by Django 5.2.17 on 2026-10-05 07:57

import cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('WRITING', '작성중'), ('CONFIRMING', '상황 확인중'), ('READY', '판결 준비완료'), ('JUDGING', '판결 진행중'), ('JUDGED', '판결 완료')], default='WRITING', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('public_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('jury_count', models.IntegerField(default=0)),
                ('fault_ratio_sum', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='CaseIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='cases.case')),
            ],
            options={
                'db_table': 'case_issues',
            },
        ),
        migrations.CreateModel(
            name='CaseSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('speakers', models.TextField(blank=True, null=True)),
                ('user_speaker_side', models.CharField(choices=[('LEFT', '왼쪽'), ('RIGHT', '오른쪽')], default='RIGHT', max_length=5)),
                ('summary', models.TextField(blank=True, null=True)),
                ('ai_raw', models.TextField(blank=True, null=True)),
                ('user_extra_context', models.TextField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('PENDING', '대기'), ('RUNNING', '분석중'), ('DONE', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='cases.case')),
            ],
            options={
                'db_table': 'case_situations',
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.ImageField(max_length=255, upload_to=cases.models.case_image_path)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.case')),
            ],
            options={
                'db_table': 'case_images',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('case', 'sort_order'), name='unique_case_image_sort_order')],
            },
        ),
    ]
