# Generated by Django 5.2.17 on 2026-10-05 07:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('VISIBLE', '표시'), ('HIDDEN', '관리자 숨김'), ('DELETED', '본인 삭제')], default='VISIBLE', max_length=10)),
                ('hidden_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jury_comments', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jury_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jury_comments',
            },
        ),
        migrations.CreateModel(
            name='JuryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_ratio', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('coin_rewarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jury_votes', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jury_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jury_votes',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('COMMENT', '댓글'), ('CASE', '사건')], max_length=10)),
                ('reason', models.CharField(choices=[('ABUSE', '욕설/비방'), ('PRIVACY', '개인정보 노출'), ('SPAM', '스팸'), ('OTHER', '기타')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('RESOLVED', '처리 완료'), ('REJECTED', '반려')], default='PENDING', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='cases.case')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='jury.jurycomment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.AddIndex(
            model_name='jurycomment',
            index=models.Index(fields=['case', 'created_at'], name='ix_comment_case_time'),
        ),
        migrations.AddIndex(
            model_name='jurycomment',
            index=models.Index(fields=['user', 'created_at'], name='ix_comment_user_time'),
        ),
        migrations.AddIndex(
            model_name='juryvote',
            index=models.Index(fields=['user', 'created_at'], name='ix_vote_user_time'),
        ),
        migrations.AddIndex(
            model_name='juryvote',
            index=models.Index(fields=['case', 'created_at'], name='ix_vote_case_time'),
        ),
        migrations.AddConstraint(
            model_name='juryvote',
            constraint=models.UniqueConstraint(fields=('case', 'user'), name='uq_vote_case_user'),
        ),
        migrations.AddConstraint(
            model_name='juryvote',
            constraint=models.CheckConstraint(condition=models.Q(('fault_ratio__gte', 0), ('fault_ratio__lte', 100)), name='ck_vote_ratio_0_100'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='ix_report_status'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'comment'), name='uq_report_comment'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'case'), name='uq_report_case'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('case__isnull', True), ('comment__isnull', False), ('target_type', 'COMMENT')), models.Q(('case__isnull', False), ('comment__isnull', True), ('target_type', 'CASE')), _connector='OR'), name='ck_report_target'),
        ),
    ]
