# Generated by Django 5.2.17 on 2026-10-05 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('CHARGE', '충전'), ('VERDICT_SPEND', '판결 사용'), ('JURY_REWARD', '배심 적립'), ('SIGNUP_BONUS', '가입 보너스'), ('VERDICT_RESTORE', '판결 실패 반환'), ('PAYMENT_REVOKE', '결제 취소 회수'), ('ADMIN_GRANT', '관리자 지급'), ('ADMIN_DEDUCT', '관리자 차감')], max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=150, unique=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_ledgers', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_coin_ledgers', to=settings.AUTH_USER_MODEL)),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_ledgers', to='payments.paymentorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coin_ledgers',
                'indexes': [models.Index(fields=['user', 'created_at'], name='ix_ledger_user_time'), models.Index(fields=['user', 'tx_type', 'created_at'], name='ix_ledger_user_type_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ck_ledger_amount_nonzero')],
            },
        ),
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coin_wallets',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='ck_wallet_balance_gte0')],
            },
        ),
    ]
